version: 2.1

orbs:
  docker: circleci/docker@1.0.0 # Invoke Docker orb

workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
          
