version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2 # Invoke the Heroku orb
  docker: circleci/docker@1.0.0 # Invoke Docker orb

workflows:
  deploy:
    jobs:
      - docker/publish:
          image: $DOCKER_LOGIN/$CIRCLE_PROJECT_REPONAME
          tag: 'latest'
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
